# generated by datamodel-codegen:
#   filename:  specs.yml
#   timestamp: 2024-04-17T12:18:51+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


class ConnectionSpecification(BaseModel):
    client_id: str
    client_secret: str
    refresh_token: str


class GoogleDriveSpecification(BaseModel):
    class Config:
        extra = 'allow'

    name: Optional[str] = 'GoogleDrive'
    module_name: Optional[str] = 'google_drive'
    protocol_version: Optional[Any] = None
    documentationUrl: Optional[str] = (
        'https://developers.google.com/drive/api/guides/about-sdk'
    )
    changelogUrl: Optional[str] = 'www.example.com'
    connection_specification: ConnectionSpecification = Field(
        ...,
        description='ConnectorDefinition specific blob. Must be a valid JSON string.',
    )
