# generated by datamodel-codegen:
#   filename:  catalog.yml
#   timestamp: 2024-04-18T11:39:43+00:00

from __future__ import annotations

from typing import List, Optional, Union
from dat_core.pydantic_models import DatDocumentStream, DatCatalog


class PostgresTableStream(DatDocumentStream):
    pass

class PostgresCatalog(DatCatalog):
    document_streams: Optional[List[Union[PostgresTableStream]]] = None