# generated by datamodel-codegen:
#   filename:  catalog.yml
#   timestamp: 2024-04-18T11:39:43+00:00

from __future__ import annotations

from typing import List, Optional

from dat_core.pydantic_models import DatDocumentStream, DatCatalog


class PostgresStream0(DatDocumentStream):
    name: Optional[str] = 'postgres_stream_0'
    property_0: str


class PostgresCatalog(DatCatalog):
    streams: Optional[List[PostgresStream0]] = None
