[project]
name = "verified-sources"
version = "0.1.0"
description = "Will host sources for the dat project"
license = {text = "MIT License"}
dependencies = [
  "pytest",
  "pydantic",
  "PyYAML",
  # TODO
  "requests",
  "lxml",
  "dat-core@git+ssh://git@github.com/riju-dc/dat-core@feature/base-classes",
  "google-api-python-client",
]

[build-system]
requires = [
    "setuptools", "wheel",
]

# [tool.setuptools.packages.find]
# exclude = ["Executables*", "Orchestrator*", ] 