# generated by datamodel-codegen:
#   filename:  specs.yml
#   timestamp: 2024-04-19T03:16:33+00:00

from __future__ import annotations

from typing import Any, Dict, Optional, Literal

from pydantic import AnyUrl, BaseModel, Field
from dat_core.pydantic_models import ConnectionSpecification

class ConnectionSpecificationModel(ConnectionSpecification):
    class Config:
        extra = 'allow'

    obj_file_path: str = Field(
        ..., description='The name of the file to be read.', title='File Path',
        json_schema_extra={'ui-opts': {'hidden': True}}
    )

    usr_file_path: str = Field(
        ..., description='The path to the file to be read.', title='File Path'
    )

class LocalFileSystemSpecification(BaseModel):
    class Config:
        extra = 'allow'

    documentation_url: Optional[AnyUrl] = None
    name: Literal['LocalFileSystem']
    module_name: Literal['local_file_system']
    connection_specification: ConnectionSpecificationModel = Field(
        ...,
        description='ConnectorDefinition specific blob. Must be a valid JSON string.',
    )
