# generated by datamodel-codegen:
#   filename:  catalog.yml
#   timestamp: 2024-04-18T11:39:43+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Field
from dat_core.pydantic_models import DatDocumentStream, DatCatalog, Advanced


class CrawlerSitemap(DatDocumentStream):
    name: Optional[str] = Field(
        'crawler_sitemap',
        description='The name of the document stream.',
    )
    namespace: Optional[str] = Field(
        None, description='namespace the data is associated with'
    )
    advanced: Optional[Advanced] = Field(
        None, description='Additional optional settings'
    )


class WebsiteCrawlerSitemapCatalog(DatCatalog):
    streams: Optional[List[CrawlerSitemap]] = None
