# generated by datamodel-codegen:
#   filename:  specs.yml
#   timestamp: 2024-04-19T03:16:33+00:00

from __future__ import annotations

from typing import Optional, Literal

from pydantic import BaseModel, Field, AnyUrl
from dat_core.pydantic_models import ConnectionSpecification

class FilterSpecification(BaseModel):
    max_depth: Optional[int]
    prefix: Optional[str]

class ConnectionSpecificationModel(ConnectionSpecification):
    site_url: str
    filter: FilterSpecification


class WebsiteCrawlerSitemapSpecification(BaseModel):
    class Config:
        extra = 'allow'

    documentation_url: Optional[AnyUrl] = None
    name: Literal['WebsiteCrawlerSitemap']
    module_name: Literal['website_crawler_sitemap']
    connection_specification: ConnectionSpecificationModel = Field(
        ...,
        description='ConnectorDefinition specific blob. Must be a valid JSON string.',
    )
