# generated by datamodel-codegen:
#   filename:  specs.yml
#   timestamp: 2024-04-17T07:33:26+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AnyUrl, BaseModel, Extra, Field


class ConnectionSpecification(BaseModel):
    site_url: str


class WebsiteCrawlerSpecification(BaseModel):
    class Config:
        extra = 'allow'

    documentation_url: Optional[AnyUrl] = None
    name: Optional[str] = 'Website Crawler'
    module_name: Optional[str] = 'website_crawler'
    connection_specification: ConnectionSpecification = Field(
        ...,
        description='ConnectorDefinition specific blob. Must be a valid JSON string.',
    )
